== jpademo

This project contains the MusicRecording/VideoRecording portion of the domain model,
and has both Hibernate and JPA versions of many of the demo
programs, including the famous (working) ManyToManyDemo.

The domain model is annotated using JPA annotations, and is used by *both
sets of demos - JPA and Hibernate - without change*.

This notion-of using both JPA and the Hibernate API to access the same entities-
is explored http://darwinsys.com/java/hibernate-jpa.html[on my Java web site].

Further, the *JPA demos can run using either Hibernate or EclipseLink
as their JPA provider*; see the persistence.xml file for the properties 
to change.

Currently works with Eclipse (M2E plugin required!) and builds with Maven; 
there are no 'run' type goals configured in Maven.

Can run with H2, HSQLDB, MySQL and PostgresQL just by changing which set
of DB parameters is not commented out in persistence.xml.

REQUIRES JAVA 8 - if you are still stuck on a legacy version of Java,
checkout revision 9084d9e1aa1ac1c261a5bf2dc8cdc8cd180b8162 and stay there
until you get a current Java SE / JDK implementation.

=== Database Setup

H2 runs in-memory, in-VM, so no setup is needed.

For PostgreSQL, you can use the handy _psql_ command-line client.
Once you have your authorization set up as per the Postgres documentation,
it can be as simple as

[source]
----
ian=# create user student login password 'student';
CREATE ROLE
ian=# create database jpademo owner student;
CREATE DATABASE
ian=# 
----

This is explored a bit more fully in the file PostgreSQL.adoc / PostgreSQL.html.

For MySQL, there is a command line client but it is very well hidden
(e.g., on Mac OS, it installs in /usr/local/mysql-5.6.21-osx10.8-x86_64/bin/mysql).
Instead, we offer a guided click-through; see the MySQL.adoc / MySQL.html
file which has many screenshots with instructions.

DO NOT USE student/student as credentials on any machine that is accessible from the Internet!!
