== jpademo

This project contains the RainForest domain model implemented using
Annotations, and has both Hibernate and JPA versions of many of the demo
programs, including the famous (working) ManyToManyDemo.

The domain model is annotated using JPA annotations, and is used by *both
sets of demos - JPA and Hibernate - without change*.

Further, the *JPA demos can run using either Hibernate or EclipseLink
as their JPA provider*; see the persistence.xml file for the properties 
to change.

Currently works with Eclipse (M2E plugin required!) and builds with Maven; 
there are no 'run' type goals configured in Maven.

Can run with H2, HSQLDB, MySQL and PostgresQL just by changing which set
of DB parameters is not commented out in persistence.xml.

=== Database Setup

H2 runs in-memory, in-VM, so no setup is needed.

For PostgreSQL, you can use the handy _psql_ command-line client.
Once you have your authorization set up as per the Postgres documentation,
it's as simple as

[source]
----
ian=# create user student login password 'student';
CREATE ROLE
ian=# create database TicketManorJava owner student;
CREATE DATABASE
ian=# 
----

For MySQL, we offer a guided click-through; see the *.doc
file which has many screenshots with instructions and has not yet been
converted to AsciiDoc format.
